# The URL the site will be built for
base_url = "https://yingmanwumen.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "Blog"
description = "Personal tech blog"
generate_feeds = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

theme = "radion"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "one-dark"

[search]
index_format = "elasticlunr_json"

[extra]
author = "yingmanwumen"
github = "https://github.com/yingmanwumen"
radion_menu = [
    {url = "$BASE_URL/", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
radion_title = "Blog"

# Nicer codeblocks with copy to clipboard
codeblock = true

# Enable MathJax support
latex = true

# Enable search bar
enable_search = true

# Light/Dark Mode set
theme = "auto" # options: {light, dark, auto, toggle}

# Whether to display favicon
favicon = false

# Giscus comment support
comments = true
giscus_repo = "yingmanwumen/yingmanwumen.github.io"
giscus_repo_id = "R_kgDOOO4Aig"
giscus_data_category_id = "DIC_kwDOOO4Ais4CoeBi"

toc = true
